In [1]:
import numpy as np  
import matplotlib.pyplot as plt  
from PIL import Image  
  
caffe_root = '/home/lqp/caffe/'  
import sys  
sys.path.insert(0, caffe_root + 'python')  
import caffe  

In [2]:
caffe.set_mode_cpu()

In [3]:
#load the model
net = caffe.Net("/home/lqp/caffe/models/bvlc_reference_caffenet/deploy.prototxt",
               "/home/lqp/caffe/models/bvlc_reference_caffenet/bvlc_reference_caffenet.caffemodel",
               caffe.TEST)

In [4]:
#load input and configure prepocessing
transformer = caffe.io.Transformer({"data":net.blobs["data"].data.shape})
transformer.set_mean("data", np.load("/home/lqp/caffe/python/caffe/imagenet/ilsvrc_2012_mean.npy").mean(1).mean(1))
transformer.set_transpose("data",(2,0,1))
transformer.set_channel_swap("data",(2,1,0))
transformer.set_raw_scale("data",255.0)

In [5]:
net.blobs["data"].reshape(1,3,227,227)

In [6]:
im = caffe.io.load_image("/home/lqp/caffe/examples/images/cat.jpg")
net.blobs["data"].data[...] = transformer.preprocess("data",im)

In [7]:
#compute
out = net.forward()

In [8]:
#predicted predicted class

In [9]:
out["prob"]

array([[  1.19005095e-09,   1.75334881e-05,   2.98291170e-08,
          1.97293861e-08,   6.59817578e-09,   4.56449243e-08,
          3.32549597e-08,   4.59545390e-07,   3.50559894e-05,
          1.17248959e-07,   1.47514959e-06,   1.06112304e-06,
          1.17827485e-05,   3.05814496e-07,   1.05061451e-06,
          1.23716757e-06,   1.18431933e-06,   1.23940608e-05,
          2.75410539e-08,   5.68765834e-09,   9.81026034e-08,
          6.76693332e-08,   3.76463838e-08,   1.67964753e-08,
          1.24188650e-08,   1.09036264e-08,   2.84512023e-08,
          4.42684787e-08,   9.56322666e-09,   5.88730472e-06,
          8.26811331e-08,   2.70075908e-08,   5.97546119e-08,
          1.28186315e-08,   1.17377565e-08,   4.91407759e-09,
          1.55577720e-08,   3.81571539e-08,   2.46796361e-08,
          3.61499737e-08,   1.25801279e-07,   5.16348990e-08,
          1.41110888e-07,   5.99132406e-08,   5.63683145e-08,
          4.05393852e-09,   2.47109512e-07,   5.53536239e-09,
        

In [10]:
out["prob"].shape

(1, 1000)

In [11]:
print(out["prob"].argmax())

281


In [12]:
labels = np.loadtxt("/home/lqp/caffe/data/ilsvrc12/synset_words.txt",str,delimiter="\t")

In [13]:
net.blobs["prob"].data[0].shape

(1000,)

In [14]:
net.blobs["prob"].data[0].flatten().argsort()

array([101, 210, 179, 228, 247, 305, 385, 243,  65, 820, 206, 116, 888,
       163, 100, 645, 119, 346, 178, 222, 983, 980, 394, 169, 217, 161,
       167, 386, 449, 267, 130, 170, 257, 256, 221, 176, 970, 147,  62,
       181, 159, 177,   0, 413, 238, 701, 180, 242, 160, 129, 444, 576,
        53, 915, 212, 211, 162, 214, 977, 389, 244, 705, 241,  50, 612,
       975, 547, 349,  48, 390, 166,  58, 525, 661, 137, 395, 345, 437,
        57,  63, 693, 821, 471, 668, 296, 110, 233, 183, 460,  49, 524,
       215, 997, 148, 764, 616, 216, 652, 660, 354, 251, 874, 164, 132,
        61,  55,  45, 486, 796,  72, 595, 944, 571, 128, 757, 229, 302,
       239, 936, 234, 511, 150, 375, 649,  35, 388, 297, 254, 609, 165,
       774, 630, 149, 900,  96, 236,  47, 615, 568, 474,  19, 727, 127,
       601, 121,  56, 755, 671, 190, 391, 425, 307, 752, 564,   4,  80,
       872, 866, 672, 655, 348, 646, 447, 597, 781, 255, 139, 146, 422,
       351, 501, 209, 889, 304, 853, 621,  69, 839, 730, 194, 53

In [15]:
top_k = net.blobs["prob"].data[0].flatten().argsort()[-1:-6:-1]

In [16]:
top_k

array([281, 282, 285, 277, 287])

In [17]:
labels[top_k]

array(['n02123045 tabby, tabby cat', 'n02123159 tiger cat',
       'n02124075 Egyptian cat', 'n02119022 red fox, Vulpes vulpes',
       'n02127052 lynx, catamount'], 
      dtype='|S131')

In [18]:
net.blobs["prob"].data[0].shape

(1000,)

In [19]:
data = np.asarray([transformer.preprocess("data",im)])

In [20]:
data.shape

(1, 3, 227, 227)